---

version: "3.7"
services:
  cycax_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEVELOPMENT=true
      - DEBUG=false
    ports:
      - 8765:8765
    volumes:
      - ./data:/data
